service:
  name: sv-api

# Add the serverless-webpack plugin
plugins:
  - serverless-aws-documentation
  - serverless-openapi-documentation
  - serverless-webpack
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-southeast-2
  stage: ${opt:stage, 'dev'}
  environment:
    ENV_PROXY_ADDR: ${file(./env-vars.json):proxyPublicAddress}
    ENV_PROXY_SK: ${file(./env-vars.json):proxySecretKey}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:ap-southeast-2:040288997789:table/Ropsten_0x1233832f5Ba901205474A0b2F407da6666aBfb08"
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:ap-southeast-2:040288997789:table/Kovan_0x1233832f5Ba901205474A0b2F407da6666aBfb08"
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:ap-southeast-2:040288997789:table/Classic_0x1233832f5Ba901205474A0b2F407da6666aBfb08"

package:
  include:
    - node_modules/websocket/**

custom:
  customDomain: ${file(sls-${self:provider.stage}-domain.yml)}
  documentation: ${file(sls-documentation.yml):documentation}
  doc: ${file(sls-documentation.yml):docFrags}
  webpackIncludeModules:
    forceInclude:
      - websocket
    # forceExclude: [ "scrypt" ]
  # webpack:
  #   webpackConfig: 'webpack.config.js'
  #   includeModules: true
  #   packager: 'npm'

functions:
  submitProxyVote:
    handler: sv/light/handlers.submitProxyVote
    timeout: 30
    events:
      - http:
          method: post
          path: /sv/light/submitProxyVote
          cors: true
          documentation:
            summary: Publish a signed vote
            requestBody:
              description: Submit a signed and packed vote for an arbitrary actor to submit to the chain on your behalf
            requestModels:
              "application/json": ProxyVoteInput
            methodResponses:
              - statusCode: 200
                responseModels:
                  "application/json": SubmitProxyVoteResp
              - ${self:custom.doc.ErrResp}
  submitProxyProposal:
    handler: sv/light/handlers.submitProxyProposal
    timeout: 30
    events:
      - http:
          method: post
          path: /sv/light/submitProxyProposal
          cors: true
          documentation:
            summary: Publish a signed vote
            requestBody:
              description: Submit a signed and packed vote for an arbitrary actor to submit to the chain on your behalf
            requestModels:
              "application/json": ProxyVoteInput
            methodResponses:
              - statusCode: 200
                responseModels:
                  "application/json": submitProxyProposalResp
              - ${self:custom.doc.ErrResp}
  submitEd25519Delegation:
    handler: sv/light/handlers.submitEd25519Delegation
    events:
      - http:
          method: post
          path: /sv/light/submitEd25519Delegation
          cors: true
          documentation:
            summary: Publish an Ed25519 -> Eth delegation (e.g. for onboarding voters from a stellar chain)
            requestBody:
              description: Submit a signed and packed ed25519 delegation for an arbitrary actor to submit to the chain on your behalf
            requestModels:
              "application/json": Ed25519DelegationReq
            methodResponses:
              - statusCode: 200
                responseModels:
                  "application/json": Ed25519DelegationResp
              - ${self:custom.doc.ErrResp}
