service:
  name: sv-api

# Add the serverless-webpack plugin
plugins:
  - serverless-aws-documentation
  - serverless-openapi-documentation
  - serverless-webpack
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-southeast-2

custom:
  customDomain: ${file(sls-${self:provider.stage}-domain.yml)}
  documentation: ${file(sls-documentation.yml):documentation}
  doc: ${file(sls-documentation.yml):docFrags}

functions:
  submitProxyVote:
    handler: sv/light/handlers.submitProxyVote
    events:
      - http:
          method: post
          path: /sv/light/submitProxyVote
          # cors: true
          documentation:
            summary: Publish a signed vote
            requestBody:
              description: Submit a signed and packed vote for an arbitrary actor to submit to the chain on your behalf
            requestModels:
              "application/json": ProxyVoteInput
            methodResponses:
              - statusCode: 200
                responseModels:
                  "application/json": TxidResponse
              - ${self:custom.doc.ErrResp}
