service:
  name: sv-api

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-southeast-2

custom:
  customDomain: ${file(sls-${self:provider.stage}-domain.yml)}

functions:
  submitProxyVote:
    handler: sv/light/handlers.submitProxyVote
    events:
      - http:
          method: post
          path: /sv/light/submitProxyVote
